import type { Metadata } from 'next';
import Navbar from '../../components/layout/Navbar';
import Footer from '../../components/layout/Footer';

export const metadata: Metadata = {
  title: 'Privacy Policy',
  description: 'Learn how Keyo Studio collects, uses, and protects your personal data.',
  alternates: { canonical: '/privacy' },
  robots: { index: true, follow: true },
};

const sections = [
  {
    title: '1. Information We Collect',
    body: `We collect information you provide directly when you create an account, such as your name, email address, and payment details. We also collect data generated by your use of our services, including prompts, generated content, usage logs, and device/browser information.`,
  },
  {
    title: '2. How We Use Your Information',
    body: `We use your data to provide and improve our AI generation services, process payments, send transactional and promotional communications (where permitted), ensure platform security, and comply with legal obligations. We do not sell your personal data to third parties.`,
  },
  {
    title: '3. Data Retention',
    body: `We retain your account data for as long as your account is active or as needed to provide services. Generated content may be stored temporarily for delivery and quality purposes. You can request deletion of your data at any time by contacting us.`,
  },
  {
    title: '4. Cookies and Tracking',
    body: `We use cookies and similar tracking technologies to maintain your session, remember preferences, and analyse platform usage. You can control cookie settings through your browser or our cookie consent banner. Disabling certain cookies may affect functionality.`,
  },
  {
    title: '5. Third-Party Services',
    body: `Our platform integrates third-party AI model providers, payment processors (Stripe), analytics tools, and authentication providers (Clerk). These services operate under their own privacy policies. We share only the minimum data necessary for them to function.`,
  },
  {
    title: '6. Your Rights',
    body: `Depending on your location, you may have rights to access, correct, delete, or restrict processing of your personal data, as well as the right to data portability. To exercise any of these rights, contact us at privacy@keyo.studio.`,
  },
  {
    title: '7. Security',
    body: `We implement industry-standard security measures including encryption in transit (TLS), secure credential storage, and regular security reviews. No method of transmission over the internet is 100% secure; we cannot guarantee absolute security.`,
  },
  {
    title: '8. Children\'s Privacy',
    body: `Keyo Studio is not directed at children under the age of 16. We do not knowingly collect personal data from children. If you believe a child has provided us with personal data, please contact us immediately.`,
  },
  {
    title: '9. Changes to This Policy',
    body: `We may update this Privacy Policy from time to time. We will notify you of significant changes by email or a prominent notice on the platform. Continued use of Keyo Studio after changes constitutes acceptance of the updated policy.`,
  },
  {
    title: '10. Contact',
    body: `If you have questions about this Privacy Policy, please contact us at privacy@keyo.studio or write to us at Keyo Studio, legal department.`,
  },
];

export default function PrivacyPage() {
  return (
    <>
      <Navbar />
      <main className="pb-20 md:pb-0" style={{ paddingTop: '60px', background: 'var(--bg)', minHeight: '100vh' }}>

        {/* Header */}
        <div style={{ padding: '48px clamp(16px,6vw,80px) 36px', borderBottom: '0.5px solid rgba(255,255,255,0.06)' }}>
          <div style={{ maxWidth: '720px', margin: '0 auto' }}>
            <div className="inline-flex items-center gap-1.5 mb-4" style={{
              background: 'rgba(83,47,207,0.1)',
              border: '0.5px solid rgba(83,47,207,0.25)',
              borderRadius: '20px', padding: '3px 10px',
            }}>
              <span style={{ color: 'rgba(120,80,255,0.8)', fontSize: '8px' }}>✦</span>
              <span className="font-dm" style={{ color: 'rgba(120,80,255,0.65)', fontSize: '10px', fontWeight: 600, letterSpacing: '1px', textTransform: 'uppercase' }}>Legal</span>
            </div>
            <h1 className="font-clash" style={{ fontSize: 'clamp(28px,5vw,48px)', fontWeight: 700, letterSpacing: '-0.03em', color: '#fff', margin: '0 0 10px' }}>
              Privacy Policy
            </h1>
            <p className="font-dm" style={{ fontSize: '13px', color: 'rgba(255,255,255,0.3)', margin: 0 }}>
              Last updated: January 1, 2026
            </p>
          </div>
        </div>

        {/* Content */}
        <div style={{ padding: '40px clamp(16px,6vw,80px) 80px' }}>
          <div style={{ maxWidth: '720px', margin: '0 auto' }}>
            <p className="font-dm" style={{ fontSize: '14px', color: 'rgba(255,255,255,0.45)', lineHeight: '1.8', marginBottom: '36px' }}>
              This Privacy Policy describes how Keyo Studio (&ldquo;we&rdquo;, &ldquo;us&rdquo;, or &ldquo;our&rdquo;) collects, uses, and shares information about you when you use our AI creative platform at keyo.studio.
            </p>

            <div style={{ display: 'flex', flexDirection: 'column', gap: '32px' }}>
              {sections.map((s) => (
                <div key={s.title}>
                  <h2 className="font-clash" style={{ fontSize: '16px', fontWeight: 600, color: 'rgba(255,255,255,0.85)', letterSpacing: '-0.01em', marginBottom: '10px' }}>
                    {s.title}
                  </h2>
                  <p className="font-dm" style={{ fontSize: '13px', color: 'rgba(255,255,255,0.4)', lineHeight: '1.8', margin: 0 }}>
                    {s.body}
                  </p>
                </div>
              ))}
            </div>
          </div>
        </div>

        <Footer />
      </main>
    </>
  );
}
